#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run phpstan
./vendor/bin/phpstan
if [ $? -ne 0 ]; then
    echo "Faça os ajustes do PHPSTAN antes de continuar... 😉";
    exit 1;
fi;

# Run tests
php artisan test --parallel | php
if [ $? -ne 0 ]; then
    echo "Verifique os testes antes de continuar... 😉";
    exit 1;
fi;

# Format each changed file with Laravel Pint
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$") || true

for FILE in $STAGED_FILES
do
    ./vendor/bin/pint "${FILE}" > /dev/null >&1;
    git add "${FILE}";
done;

exit 0;